version: "3.3"

services:
  pyphp:
    build: .
#    image: influxdb:alpine
    ports:
      - "5000:5000"
#    environment:
#      - INFLUXDB_GRAPHITE_ENABLED=true
#      - INFLUXDB_ADMIN_ENABLED=true
#      - INFLUXDB_REPORTING_DISABLED=false
#      - INFLUXDB_DATA_QUERY_LOG_ENABLED=true
#    volumes:
#      - ${DATA_SAVE_PATH}/influxdb:/var/lib/influxdb
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

